VIA_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
LAYER_LOCK_ENABLE = yes

OPT_DEFS += -DWIRELESS_RAW_ENABLE

KEYMAP_INTROSPECTION = no

# THIS FILE CANNOT BE NAMED keymap.cpp NOR main.cpp BECAUSE QMK BUILD SYSTEM IGNORES IT
SRC += Keymap.cpp
